- demo/client/src/camera.ts
Currently movement works in the direction of the latest key pressed.
Moving diagonally is not possible, and if you are pressing two keys
and release one, movement stops instead of switching over.
This keeps track of the key press state and updates the movement delta
accordingly.
Note than onKeyDown is called multiple times when you press and hold,
so we must keep track of this state ourselves.
> demo/client: Make WASD composable

- demo/client/html/svg-demo.html.hbs
- demo/client/html/text-demo.html.hbs
- demo/client/src/app-controller.ts
- demo/client/src/camera.ts
- demo/client/src/view.ts
Depends on #38 
This PR adds a Zoom Pulse button to slowly zoom in and out the Text and SVG demo. The goal is to demonstrate how smooth rendering is.
> Zoom Pulse Mode

- demo/client/css/pathfinder.css
- demo/client/html/mesh-debugger.html.hbs
- demo/client/src/mesh-debugger.ts
Depends on #44 
This PR adds the ability to draw the hull along with the control points. When I first saw the control points floating in space I was confused by it, I thought drawing the hull helps.
This PR also adds ability to toggle the visualization of vertices `v`, control points `c` and normals `n` using the keyboard.
> Mesh Debugger Improvements

- shaders/gles2/common.inc.glsl
See #51. This works around a bug in the macOS Nvidia shader compiler in 2014 rMBPs. The fix shows that as suspected this is very clearly a GPU bug. The funny part is that the compiler is clearly not great since putting the condition in a variable that isn't used anywhere shouldn't make much difference to a competent compiler.
I hope putting the condition in a variable doesn't significantly regress performance on other platforms. Might be worth a benchmark.
I also removed the unused `lineDoesNotPassThroughPixel` function.
cc @pcwalton @mmastrac
> Fixes #51 by introducing a variable for an early return boolean.

- font-renderer/src/core_graphics.rs
I'm pretty confident that it is only thread safe if FK is (or another way of putting it is, I'm pretty sure if you include an `Rc<_>` in FK it should not be safe to share between threads).
> The Send impl for `FontContext` is too forgiving.

- demo/client/html/3d-demo.html.hbs
- demo/client/package.json
- demo/client/src/3d-demo.ts
- demo/client/src/aa-strategy.ts
- demo/client/src/app-controller.ts
- demo/client/src/camera.ts
- demo/client/src/renderer.ts
- demo/client/src/ssaa-strategy.ts
- demo/client/src/view.ts
- demo/client/src/xcaa-strategy.ts
- demo/client/tsconfig.json
- shaders/gles2/common.inc.glsl
- shaders/gles2/demo-3d-monument.fs.glsl
Actually mergeable.
I still want to improve the camera code. It currently just overwrites the rotation matrix, but we can do better.
Ideally the code gets refactored into having two view transforms.
r? @pcwalton
> Cleaned up VR implementation

- font-renderer/src/directwrite/mod.rs
- font-renderer/src/lib.rs
See https://github.com/servo/webrender/issues/2645 - this fixes 2 of the 6 errors I get when compiling webrender on Windows. 
I decided to use the same API that is used for Mac & Linux builds, with the extra `exact` parameter and returning an Error instead of an Option. Maybe it would be a good idea to change it back to `Option` instead of `Err<()>`, but then please change it in all 3 APIs.
> Fix the API of glyph_dimensions to make webrender compile on Windows

- README.md
My normal workflow involves using tools that are mostly in "JavaScript land". So, I didn't have either Rust or CMake installed. The instructions mentioned Rust nightly builds as a dependency, but not CMake. So, I've added CMake and then turned each of these dependencies into a link as a convenience for anyone that comes along later.
Fixes #86
> docs(readme): clarify demo build requirements

- font-renderer/src/freetype/outline.rs
In `font-renderer/src/freetype/outline.rs` there's an assumption that `c_char` is `i8`, so it fails to compile on architectures where `c_char` is `u8`:
```
info: component 'rust-std' for target 'aarch64-linux-android' is up to date
Compiling pathfinder_font_renderer v0.5.0 (/Users/ajeffrey/github/asajeffrey/pathfinder/font-renderer)
Compiling script_layout_interface v0.0.1 (/Users/ajeffrey/github/asajeffrey/servo/components/script_layout_interface)
Compiling layout_traits v0.0.1 (/Users/ajeffrey/github/asajeffrey/servo/components/layout_traits)
error[E0308]: mismatched types
--> /Users/ajeffrey/github/asajeffrey/pathfinder/font-renderer/src/freetype/outline.rs:65:24
|
65 |             (position, tag)
|                        ^^^ expected i8, found u8
error: aborting due to previous error …
```
> Outline tags are chars not i8s

- demo/common/src/lib.rs
- demo/common/src/window.rs
- gl/src/lib.rs
Allows using pathfinder when the default framebuffer is non-zero (e.g. on ML1).
> Allow a non-zero default framebuffer

- demo/android/rust/src/lib.rs
- demo/common/src/lib.rs
- demo/common/src/window.rs
- demo/native/src/main.rs
A couple of changes to option-handling:
- allow demo apps to provide default options
- add an option to disable the UI
> A couple of features for Options

- demo/android/rust/src/lib.rs
- demo/common/src/window.rs
- demo/native/src/main.rs
This allows the window to cache some data without using interior mutability.
> Make the demo window present method take a &mut self

- demo/common/src/lib.rs
This gets rid of one frame of latency when there are events (e.g. pose data in VR) which affect the scene.
> In the demo, handle events before updating the scene

- demo/common/src/lib.rs
- demo/common/src/window.rs
Allow the device to set different camera transforms for each eye.
> Allow devices to set transforms for each camera

- renderer/src/gpu/renderer.rs
Fixes #134.
glVertexAttribPointer takes a size as parameter which refers to the number of components and not the size in bytes of the value.
The tile index was registered as a 2-components value which caused the second component to overlap with the first member of the next primitive, which was mostly fine except for the last element which would overlfow the buffer. Intel and nvidia GPUs/drivers on linux at least refuse to read the first component of this two-component value if the other component is outside of the valid range which caused the shader to get zero instead and always select the first mask tile.
> Fix vertex attribute configuration of alpha tiles

- simd/src/scalar/mod.rs
Silencing the following rustc warning:
warning: unused variable: `other`
Followup to Pull Request #152 
Instead of marking `other` unused (`_other`) we can remove the method
entirely.
> Remove cross method from F32x4

- gl/src/lib.rs
Okay, I have no idea if this PR contains the right kind of change for pathfinder, but I figured it'd start a conversation, at least.
Basically, when addressing the problem of dynamically resizing the in-editor Unity player mentioned in https://github.com/pcwalton/pathfinder/issues/147#issuecomment-496015315 (e.g., when the user clicks "play" and then resizes their window), I found that the approach used in Pathfinder's demo code didn't fully work in Unity:
https://github.com/pcwalton/pathfinder/blob/bc713a5181ab7ed90469d054c36f78baed36b306/demo/common/src/lib.rs#L266-L274
Specifically, what happens is that the Pathfinder rendering simply disappears every time I resize the window, though it occasionally/randomly comes back into view.  I tried simply re-instantiating the whole `Renderer` …
> Add GLDevice::set_default_framebuffer()

- gl/src/lib.rs
Fixing the following warning
warning: unused variable: `resources`
Small but I saw this warning will starting to write tests.
> Fix unused variable warning

- simd/src/test.rs
This raises the test coverage in SIMD from 10.04% to 10.27%, just a bit.
@pcwalton, I see there is a comment about completing I32x4 swizzles, do you want me to do that? In this commit I'm only testing the 4 that exist.
> Add test_i32x4_swizzles

- simd/src/test.rs
This isn't complete but I wanted to check with you that the structure is OK.
> Start adding tests for scalar::F32x4

- demo/common/src/lib.rs
- demo/common/src/renderer.rs
- demo/common/src/window.rs
- demo/magicleap/src/lib.rs
- demo/magicleap/src/magicleap.rs
- demo/magicleap/src/main.cpp
These are the changes needed to get the magicleap demo running again. There are some minor changes to the common demo, the main one is calling `make_current` for each eye during rendering, previously we were assuming the only difference between eyes was the viewport.
> Get magicleap working again

- c/src/lib.rs
As mentioned in #179, I thought mentioning that `PFCanvasCreate()` consumes the font context might help make its usage a bit clearer.
> Mention PFCanvasCreate() consumes the font context

- .travis.yml
- add cmake via apt
- replace demo builds with root-level `cargo build`
`cargo test` works, too, but there are a couple failing tests so I commented it out.
> full build in CI

- simd/src/test.rs
This brings the coverage up to 21.21%
I will add the same tests for I32x4 next.
> Add more tests for F32x4

- gl/src/lib.rs
While attempting to investigate https://github.com/servo/pathfinder/issues/178, I noticed that the `ck()` function, which checks to see if there's a GL error and panics if so, wasn't running on my debug build.  Its definition was conditional based on whether `cfg(debug)` is set, but I'm not actually sure what that is or how to set it, whereas [`cfg(debug_assertions)` does the trick](https://stackoverflow.com/a/39205417/2422398).
This PR changes the conditional compilation to be based on `debug_assertions`.  However, if that's not the right way to approach this, please let me know!
> Define ck() based on cfg(debug_assertions)

- demo/common/src/lib.rs
- demo/magicleap/src/main.cpp
- geometry/src/basic/transform3d.rs
At the moment on magicleap, and any other platform which uses `SetEyeTransforms`, the scene transform is not updated when the eye transforms are, which results in blurry rendering, especially visible on text. This PR fixes that.
> Improve reprojection on magicleap

- text/src/lib.rs
I think this should be the correct approach. At least it renders text properly with a transformation containing a scale component of != 1.
The Demo still renders properly and it fixes some funny glitches.
> SceneExt::push_layout make transform apply to offsets

- c/src/lib.rs
This exposes the Canvas' transform and save/restore functionality to the C API.
The only method I haven't added here is `Canvas::current_transform()`, which I can add for completeness if you want.
> Expose Canvas transform and save/restore to C

- c/Cargo.toml
- canvas/Cargo.toml
- canvas/src/lib.rs
- canvas/src/text.rs
- canvas/src/text_no_text.rs
- examples/canvas_metal_minimal/Cargo.toml
- examples/canvas_moire/Cargo.toml
- examples/canvas_text/Cargo.toml
> Make text rendering optional in pathfinder_canvas

- Cargo.lock
- c/Cargo.toml
- canvas/Cargo.toml
- examples/canvas_text/Cargo.toml
- text/Cargo.toml
- text/src/lib.rs
Hi. This bumps font-kit, lyon, and skribo versions to fix a crash in the canvas_text program which was a result of a bug in font-kit which seemed to have been fixed in [this commit](https://github.com/servo/font-kit/commit/354496bc0e4cf74ad3590c29d8bb7c6d5058ab1f#diff-c91947245798d9a47636805a747f5159), yet since pathfinder and its dependencies were using an older version of font-kit, it did not receive this fix. As a result, canvas_text would crash with the following:
>thread 'main' panicked at 'assertion failed: *current_point_index <= last_point_index_in_contour', /home/kamal/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.2.0/src/loaders/freetype.rs:576:13
This patch bumps font-kit versions in pathfinder's dependencies and fixes the breaking changes that come with it. I've …
> Bump lyon, font-kit and skribo versions to fix crashes

- renderer/src/sorted_vector.rs
During profiling of the PDF viewer, SortedVector::push showed up at 44% when displaying the Inkscape about screen (converted to PDF).
Switching to `slice::binary_search_by` made it disappear.
> use a binary search for pathfinder_renderer::SortedVector

- simd/src/x86/mod.rs
- simd/src/x86/swizzle_f32x4.rs
- simd/src/x86/swizzle_i32x4.rs
> Support `pathfinder_simd` on 32-bit x86.

- Cargo.lock
- content/Cargo.toml
`quickcheck` usage in `pathfinder_content` had been added in b8f622203ae96776fe69a0c10282792832db9ef2, but not to the `Cargo.toml`.
This makes tests pass again.
> Add quickcheck build-dependency

- demo/common/Cargo.toml
- geometry/Cargo.toml
- gl/Cargo.toml
- renderer/Cargo.toml
pathfinder-geometry enabled a log feature that restricts logging to warn for any binary using it.
This is really hard to find for anyone using the package as suddenly logging seems to stop working for no apparent reason
> Remove log restriction

- Cargo.lock
- renderer/Cargo.toml
- renderer/src/builder.rs
- webgl/Cargo.toml
This PR fixes several problems to make pathfinder fully available to wasm32. Including:
- Use `instant` crate instead of `std::time::Instant` to compile to wasm32 (only changed in wasm32 available subcrates)
- fix the `pathfinder_resources` dependency in webgl module
> Use instant crate to build for wasm32 target

- canvas/src/text_no_text.rs
I think this should match the text version  to make it easier to swap between them.
> Add derive(Clone) to no text font context

- canvas/src/lib.rs
Export types need to use the canvas API from other pathfinder crates.
From pathfinder-color all types and convinience functions are exported.
From pathfinder-geometry only the 2D vector and rect types with
their convinience functions are exported.
Items from pathfinder-renderer are not re-exported as they also
belong to the back-end.
Pattern, while used in the canvas API, is not re-exported as
it is not needed for basic usage and depends on a lot of other types.
See #283
> Re-export necessary items in pathfinder-canvas

- c/cbindgen.toml
> Provide a placeholder definition of `CAMetalLayer` in the C API.

- c/src/lib.rs
> Document `PFCanvasFontContextCreateWithFonts()`.

- gl/src/lib.rs
- gpu/src/lib.rs
- metal/src/lib.rs
- renderer/src/gpu/renderer.rs
- renderer/src/gpu/shaders.rs
- ui/src/lib.rs
- webgl/src/lib.rs
Also, ensure there is always a dummy texture bound to every parameter in the
OpenGL backend.
These together stop the macOS Radeon drivers from recompiling the shader on
every drawcall.
Possibly addresses #300.
> Associate texture parameters in shaders with specific texture units, to work around a macOS Radeon driver bug.

- simd/src/scalar/mod.rs
These were added to the other simd implementations, but left out of the scalar implementation, leading to build errors when using feature "pf-no-simd" (or building on a platform without hardware simd).
> Implement BitAnd, BitOr, and Not for U32x2 in scalar version.

- resources/MANIFEST
This fixes an issue that caused `pathfinder_metal` to panic when [attempting to load shaders](https://github.com/servo/pathfinder/blob/0f3500921596bdb2924d7bd62c4f983afc9332ec/metal/src/lib.rs#L854) using the embedded resource loader.
/cc: @nathansobo
> Add missing Metal shader to resources/MANIFEST

- c/src/lib.rs
Its only use is for `CoreAnimationLayerRef::from_ptr()` in `PFMetalDeviceCreate`, so this fixes a warning on other platforms.
The last time I tried to fix this warning I didn’t notice that it was actually used, and thus 2d2bc14e5cb597bc9c8f602d28c4a16902fd1938 broke the macOS build in #257.
> Only use foreign-types on macOS in the C API

- c/src/lib.rs
This is useful when Pathfinder is shipped by a Linux distribution, and not with everything bundled.
> Expose creating a resource loader from a path to C

- svg/src/lib.rs
> `usvg` should never have nested `<svg>` nodes, so remove code that (doesn't) handle that case.

- Cargo.lock
- c/Cargo.toml
- c/cbindgen.toml
- c/src/lib.rs
- demo/common/Cargo.toml
- demo/native/Cargo.toml
- demo/native/src/main.rs
- examples/canvas_metal_minimal/Cargo.toml
- examples/canvas_metal_minimal/src/main.rs
- examples/canvas_nanovg/src/main.rs
- examples/macos_app/Pathfinder Example.xcodeproj/project.pbxproj
- examples/macos_app/Pathfinder Example.xcodeproj/xcshareddata/xcschemes/Pathfinder Example.xcscheme
- examples/macos_app/Pathfinder Example.xcodeproj/xcuserdata/pcwalton.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
- examples/macos_app/Pathfinder Example/PathfinderView.h
- examples/macos_app/Pathfinder Example/PathfinderView.m
- metal/Cargo.toml
- metal/src/lib.rs
- renderer/src/gpu/d3d11/renderer.rs
- renderer/src/gpu/d3d9/renderer.rs
- renderer/src/gpu/renderer.rs
- resources/shaders/gl4/d3d11/tile.cs.glsl
- resources/shaders/metal/d3d11/tile.cs.metal
- shaders/d3d11/tile.cs.glsl
`winit` does not create an autorelease pool, so the Metal backend had not taken
the presence of one into account. Now the Metal backend creates and flushes
autorelease pools as necessary.
Closes #334.
Closes #376.
> Fix Metal memory management and the `canvas_metal_minimal`, `canvas_nanovg`, and `macos_app` examples.

- c/src/lib.rs
This PR exposes the c api to the EmbeddedResourceLoader, to prevent some of the issues mentioned [here](https://github.com/servo/pathfinder/issues/234). 
- Followed `PFFilesystemResourceLoaderLocate` and simply exposed the ERL's new and boxed it in the ResourceLoaderWrapper
- Used the `Create` terminology in the signature to match the rest of the api where a new() is called
- I successfully tested it in a little .NET binding project I'm working on.
- Moved the \`gl\` section comment down with the GL methods, as it seemed a little out of place. added a \`resources\` one. then moved the destroy fn in to the new section.
Let me know if I misinterpreted anything or if there are any changes, stylistic or otherwise, that you'd prefer. Thanks!
> Expose EmbeddedResourceLoader to c api

- renderer/src/builder.rs
- renderer/src/gpu_data.rs
- renderer/src/scene.rs
- renderer/src/tiler.rs
- renderer/src/tiles.rs
- resources/shaders/gl4/d3d11/propagate.cs.glsl
- resources/shaders/metal/d3d11/propagate.cs.metal
- shaders/d3d11/propagate.cs.glsl
- svg/src/lib.rs
> Implement nested SVG clip paths in the D3D11 backend.

- renderer/src/gpu/d3d11/renderer.rs
- renderer/src/gpu/d3d11/shaders.rs
- resources/shaders/gl4/d3d11/propagate.cs.glsl
- resources/shaders/gl4/d3d11/sort.cs.glsl
- resources/shaders/metal/d3d11/propagate.cs.metal
- resources/shaders/metal/d3d11/sort.cs.metal
- shaders/d3d11/propagate.cs.glsl
- shaders/d3d11/sort.cs.glsl
Apparently Mesa RadeonSI drivers have a limit of 8 SSBOs.
Closes #373.
> Combine the Z-buffer and fill indirect draw params buffers to reduce the number of SSBO bindings.

- content/src/pattern.rs
- examples/canvas_nanovg/src/main.rs
- renderer/src/allocator.rs
- renderer/src/builder.rs
- renderer/src/paint.rs
- renderer/src/scene.rs
Images are cached for one frame; if they are not used the next frame, they're
freed.
> Cache images from frame to frame.

- examples/canvas_text/src/main.rs
Before this change, the `canvas_text` example would become blank after
navigating to another workspace or being put beneath another window.
This change will listen for the SDL window exposed event, and will
render then instead of only at the beginning.
> Make `canvas_text` example render on expose

- c/src/lib.rs
- canvas/src/text.rs
- examples/canvas_nanovg/src/main.rs
- text/src/lib.rs
This adds an extension to the HTML canvas API that allows you to pass the
`TextMetrics` object returned by `measure_text()` to `fill_text()` and/or
`stroke_text()` to draw the measured text without laying it out again. It
improves performance on the `canvas_nanovg` demo.
> Make the fields of `TextMetrics` lazily calculated, and add an API that eliminates double layouts.

- examples/canvas_minimal/src/main.rs
I'm not sure if this actually works, because the `canvas_minimal` example doesn't run on my computer.
> Make `canvas_minimal` example rerender on refresh

- resources/shaders/gl3/d3d9/tile.fs.glsl
- resources/shaders/gl4/d3d11/tile.cs.glsl
- resources/shaders/gl4/d3d9/tile.fs.glsl
- resources/shaders/metal/d3d11/tile.cs.metal
- resources/shaders/metal/d3d9/tile.fs.metal
- shaders/tile_fragment.inc.glsl
> Allow radial gradients to be evaluated with any nonzero discriminant, not just ones with magnitude above `EPSILON`.

- renderer/src/gpu/renderer.rs
> Initialize resized mask textures to rgba(0, 0, 0, 0), not rgba(0, 0, 0, 1).

- canvas/src/lib.rs
> Allow clip paths to nest in the canvas API.

- content/src/clip.rs
There was a spelling mistake in `clip::clip_line_segment_to_rect`
the `if-else` expression made repeated judgments for `Outcode::LEFT`
see: https://github.com/servo/pathfinder/issues/436
> bugfix #436 which endless loop in clip::clip_line_segment_to_rect method

- simd/src/arm/mod.rs
According to packed_simd docs, the syntax for simd_shuffle4()
is as follows:
"The indices must be in range [0, M * N) where M is the number of input
vectors (1 or 2)and N is the number of lanes of the input vectors. The
indices i in range [0, N) refer to the i-th element of vec0, while the
indices in range [N, 2*N) refer to the i - N-th element of vec1."
I did not find implementation or documentation for simd_shuffle4() but
I believe packed_simd implements exactly the same interface.
Plus, implementing this change has fixed font-kit glyph output on
an Apple M1 mac (64-bit arm).
Closes #450
> Fix arm simd shuffling arguments

- export/src/lib.rs
Presently, when serializing to SVG, the `fill` attribute is being populated with a `PaintId` identifier, e.g.:
```svg
<path fill="PaintId(1)" d="M 0 0 L 431.8 0 L 431.8 279.4 L 0 279.4 z" />
```
This PR instead utilizes the base color, which results in the following alternative output:
```svg
<path fill="#ffffff" d="M 0 0 L 431.8 0 L 431.8 279.4 L 0 279.4 z" />
```
> Passing actual color in fill attribute

- svg/src/lib.rs
1. Order of application of transformations: While processing a
path the order of transformations are from the inner most to the
outer most.
For example: In the graphic
```xml
<svg>
<g transform=A>
<g transform=B>
<path ... />
</g>
</g>
</svg>
```
Path control points will be calculated by pre-multiplying
with A * B, not B * A as per the current code.
2. Applying transformation to clip paths: The transformations
of the ancestors are applied to the clip path property of a path.
For example:
```xml
<svg>
<defs>
<clipPath id="clippath">
<path id="clipper" ... />
<clipPath/>
</defs>
<g transform=A>
<path id="clippee" clip-path="url(#clippath)" ... />
</g>
</svg>
```
Then, the transform A is applied to both the clippee and
the clipper.
> Fixing svg parsing

- examples/canvas_nanovg/Cargo.toml
- examples/canvas_nanovg/src/main.rs
The `canvas_nanovg` example would not run on my Linux machine due to the bug in `winit` 0.19 (rust-windowing/winit#1773)
In this PR, I updated `winit` and `surfman` and made the minimum necessary changes so that the example would compile and run.
> Update canvas_nanovg example

- content/src/clip.rs
Fix the artifact caused by view box clipping on d3d9 level. Note that d3d11 doesn't have this issue.
> Fix Cohen-Sutherland algorithm implementation for d3d9

- canvas/src/lib.rs
At present pathfinder_canvas treats the offset of sx/sy in draw_subimage as offsets in the destination canvas's coordinate space (See #481).
In order to match the behaviour of the html canvas API, these should be treated as offsets in the source image's coordinate space.
This fixes https://github.com/servo/pathfinder/issues/481. You can check the implementation against https://github.com/Adjective-Object/pathfinder_canvas_drawimage_repro.
For a quick visual reference, in these before/after images, the right side is made with the web canvas API In firefox, and the left side is the equivalent code in pathfinder_canvas.
Before:  ![image](https://user-images.githubusercontent.com/1174858/143279607-a862327d-e9e4-4fd3-8baf-09f7426772a8.png)
After: …
> Scale offset in source image's own coordinate space

- c/Cargo.toml
It also possibly simplifies the building instructions since it will pick automatically the crates in the workspace marked with a `capi` feature.
> Add a capi feature to support current cargo-c

- Cargo.lock
- demo/native/src/main.rs
- examples/swf_basic/src/main.rs
Only doing this to remedy a very minor annoyance of mine. These are not major (or even very helpful) changes by any measure.
- Removes an unneeded `use` statement
- Fixes a [deprecated](https://doc.rust-lang.org/nightly/edition-guide/rust-2021/panic-macro-consistency.html) use of `panic!`
> Extremely minor fixes

- simd/src/test.rs
The test function body is probably incorrect. The right-hand side produces values which are incorrect in the CI run as well. Everything else seems to be fine.
This can be verified when using only the simd intrinsics as defined in the [core library](https://rust-lang.github.io/stdarch/x86_64/core_arch/x86_64/fn._mm_rcp_ps.html).
```rust
fn main() {
#[cfg(target_arch = "x86")]
use std::arch::x86::*;
#[cfg(target_arch = "x86_64")]
use std::arch::x86_64::*;
unsafe {
let values = _mm_set_ps(1.0, 3.0, 5.0, 7.0);
let res = _mm_rcp_ps(values);
println!("{:?}", values);
println!("{:?}", res);
}
}
```
produces
```bash
__m128(7.0, 5.0, 3.0, 1.0)
__m128(0.14282227, 0.19995117, 0.333313, 0.99975586)
```
Notice that the order in the output is different compared to its specification inline but the …
> fix f32x4_basic_ops test

- simd/Cargo.toml
This is a follow-up of #548 to push simd upstream.
> bump simd to 0.5.3 in order push fixes for stdsimd feature upstream

- simd/src/arm/mod.rs
- simd/src/lib.rs
Make pathfinder_simd work on latest nightly.
Fixes #558
> Replace platform-intrinsic  with core_intrinsics

- Cargo.lock
- simd/src/arm/mod.rs
- The tests didn't compile, there were some methods missing
- `F32x4::concat_xy_xy` was wrong and failing the tests
> pathfinder_simd fixes for ARM
