- demo/client/webpack.config.js
> Fix demo client compilation on Windows

- font-renderer/src/freetype/mod.rs
- font-renderer/src/lib.rs
- font-renderer/src/tests.rs
Revives the tests again. But I don't know why they are failing.
> Make tests compile again (but not pass)

- font-renderer/src/directwrite/mod.rs
The dimensions in the `DWRITE_GLYPH_METRICS` are a bit special: the `rightSideBearing` is measured from the right edge of the character boundary, not the left edge.
So, doing (right - left) would usually return a negative or very small number, which, when casted to a u32 in an unsafe block, would silently overflow to a very large number and make webrender crash.
Therefore, in order to calculate the metrics correctly, we have to first calculate the full width of the character, then subtract the right and left edges, same width the height.
> Fixed calculation of glyph dimensions on Windows

- simd/src/scalar.rs
This code looks like it was generated by a script but all of the lines are missing a closing square bracket. With this the pf3 branch compiles again (without any feature flag).
> Fix swizzles in scalar.rs

- geometry/src/basic/transform3d.rs
Add a convenience method to multiply a Perspective by a Transform.
> Add Perspective::post_mul

- demo/common/src/lib.rs
- demo/common/src/window.rs
This is useful for platforms like magicleap which need to set up CPU affinity for threads.
> Allow the Window to customize rayon's thread builder

- demo/android/rust/src/lib.rs
- demo/common/src/lib.rs
- demo/common/src/window.rs
- demo/native/src/main.rs
This makes the Window determine the viewports, not the demo appl
> Allow devices to determine the viewport for each eye

- demo/magicleap/.cargo/config
- demo/magicleap/Cargo.toml
- demo/magicleap/src/lib.rs
Updated for the latest pf3 API.
Also explicitly set the linker flavor, to mitigate https://github.com/rust-lang/rust/issues/55396
> Pathfinder magicleap demo updates

- renderer/src/builder.rs
- renderer/src/gpu/renderer.rs
- renderer/src/gpu_data.rs
This is an attempt to address: https://github.com/pcwalton/pathfinder/issues/135
Tiger seems to render correctly.
> Constrain sizes of solid tile and alpha tile batches being sent to the GPU

- Cargo.lock
- renderer/Cargo.toml
This dedupes some dependencies
> Update quickcheck to 0.8

- demo/magicleap/src/main.cpp
LuminOS 0.96 now requires lifecycle initialization to happen before other initialization.
Fixes #186.
> Fix the magicleap app to work in LuminOS 0.96

- Cargo.lock
- renderer/Cargo.toml
Found with [cargo-udeps](https://github.com/est31/cargo-udeps)
> Remove redundant fixedbitset dependency

- .travis.yml
- geometry/src/vector.rs
- simd/src/arm/mod.rs
This at least exposes various compilation errors that I'm encountering when building for windows arm64.
Fix #297. Fix #295. Fix #294.
> Add arm64 CI and fix build errors

- renderer/src/gpu/renderer.rs
- renderer/src/gpu/shaders.rs
- resources/shaders/gl3/clear.fs.glsl
- resources/shaders/gl3/clear.vs.glsl
- resources/shaders/gl4/clear.fs.glsl
- resources/shaders/gl4/clear.vs.glsl
- resources/shaders/gl4/tile_fill.cs.glsl
- resources/shaders/gl4/tile_fill.fs.glsl
- resources/shaders/gl4/tile_fill.vs.glsl
- resources/shaders/metal/clear.fs.metal
- resources/shaders/metal/clear.vs.metal
- resources/shaders/metal/tile.fs.metal
- shaders/Makefile
- shaders/clear.fs.glsl
- shaders/clear.vs.glsl
> Clear the canvas to the background color if no drawing command did so.

- Cargo.lock
- demo/native/Cargo.toml
- examples/canvas_minimal/Cargo.toml
- examples/canvas_moire/Cargo.toml
- examples/canvas_nanovg/Cargo.toml
> Switch to using surfman in X11 mode.

- Cargo.lock
- demo/native/Cargo.toml
- examples/canvas_minimal/Cargo.toml
- examples/canvas_moire/Cargo.toml
- examples/canvas_nanovg/Cargo.toml
> Upgrade to the latest master surfman

- .gitignore
- c/cbindgen.toml
- examples/c_canvas_glfw_minimal/Makefile
- examples/c_canvas_glfw_minimal/c_canvas_glfw_minimal.c
> Add an example showing how to use the Pathfinder C API with GLFW

- examples/canvas_glutin_minimal/src/main.rs
- examples/canvas_metal_minimal/src/main.rs
- examples/canvas_moire/src/main.rs
- examples/canvas_nanovg/src/main.rs
- examples/canvas_text/src/main.rs
- examples/swf_basic/src/main.rs
https://github.com/servo/pathfinder/issues/234#issuecomment-626042606
> Switch to the embedded loader for the examples.

- c/src/lib.rs
>  Expose OpenGL 4.x in the C bindings 

- Cargo.lock
- c/Cargo.toml
- c/src/lib.rs
- demo/common/src/lib.rs
- demo/magicleap/src/immersive.rs
- demo/magicleap/src/lib.rs
- svg/src/lib.rs
- utils/convert/src/main.rs
> Expose `pathfinder_svg` to the C API

- svg/src/lib.rs
> Fix `Display` impl on `BuildResultFlags`

- renderer/src/gpu/d3d11/renderer.rs
- renderer/src/gpu/d3d9/renderer.rs
- renderer/src/gpu/perf.rs
- renderer/src/gpu/renderer.rs
> Turn off timer queries if the debug UI is off.

- content/src/gradient.rs
- renderer/src/paint.rs
- svg/src/lib.rs
> Implement gradient wrap/spread modes in SVG.

- renderer/src/paint.rs
> Add 1px of texture border around non-repeating image patterns.

- content/src/clip.rs
- renderer/src/builder.rs
- renderer/src/tiler.rs
>  Clip line segments before tiling them, and remove the cap on the number of iterations when tiling.

- canvas/src/lib.rs
> Implement `putImageData()` on canvas.

- c/cbindgen.toml
Attempts to fix [issue #422](https://github.com/servo/pathfinder/issues/422).
> Add [defines] section to cbindgen.toml

- c/src/lib.rs
> Expose `CanvasRenderingContext2D::set_text_baseline()` to C.

- resources/shaders/README.md
- shaders/Makefile
- shaders/README.md
This changelist expands the documentation around what it takes to regenerate/build the shaders.
Closes #346.
> Add docs for building shaders on Windows

- simd/src/arm/mod.rs
- simd/src/arm/swizzle_f32x4.rs
- simd/src/arm/swizzle_i32x4.rs
> Stop using old-style simd_shuffle

- simd/src/arm/mod.rs
See https://github.com/servo/pathfinder/issues/545
> copy PartialEq impl from F32x4 for F32x2

- simd/src/lib.rs
> Remove stdarch_arm_crc32 feature as it is now stable

- simd/Cargo.toml
Pulls in #566 and allows building on nightly
> New release 0.5.4

- simd/Cargo.toml
Release mainly for #575 in order to build on nightly
> Update Cargo.toml to release fixes to build on nightly
